var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                             o  ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                           p                    ",
   "                                                    xxyxxyxx                    ",
   "                                                    v v v v                     ",
   "                                    o o                                         ",
   "                                                                                ",
   "                                   xxxxx                                        ",
   "                                                                                ",
   "                                          o o                                   ",
   "                                                                                ",
   "                                         xxxxx              xx                  ",
   "                                                            x   =   =           ",
   "     @                  o                                   x =   =   =         ",
   "xxxxxxxxxyyyyyyyyyyyyyyxxxyyyyyyyyyyyyyyyyyyyyyyyyyy        xxxxxxxxxxx        x",
   "                                                   x!!!!!!!!x         x        x",
   "                                                   x!!!!!!!!x         x        x",
   "                                                   x!!!!!!!!x         x        x",
   "                                                   xxxxxxxxxx         x        x",
   "                                                                      x        x",
   "                                                                      xyyyyyyyyx"],
  ["                                                                                                               xx!",
   "                                                                                                              x!!!",
   "                                                                                                              x!!!",
   "                                                                                                              x!!!",
   "                                                                                                              x!!!",
   "                                                                   o   o                                     xx!!!",
   "                                                                                               xxxxxxxxxxxxxxx!!!!",
   "                                                                   x   x                  !!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                             xx             xx           !!xxxxxxxxxxxxxxxxxxxxxxx",
   "                                                              xx!!!!!!!!!!!xx            vv                       ",
   "                                                               xxxx!!!!!xxxx                                      ",
   "                                               x     x            xxxxxxx         xx         x                    ",
   "                                               x     x                             x         x                    ",
   "                                               x     x                             x         x                    ",
   "                                               x     x                             xx        x                    ",
   "                                               xx    x                   p         x         x                    ",
   "                                               x     x      o  o        xxx        x         x                    ",
   "              xxxxxxxxx                        x     x                             x       yyx                    ",
   "                                               x     x     xxxxxx            xxxxxxxxx       x                    ",
   "                                x   x          x    xx                       x               x                    ",
   "     @                          x   x          x     x                       x               x                    ",
   "    xxx      x         x        x   x          x     x                       x   xxxxxx      x                    ",
   "    x x      x         x       xx o xx         x     x                             x    =    x                    ",
   "!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!!!                 x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxvxxxvx     x!!!!!!!xx!!!                 xy  o o  yx                    ",
   "!!!!x x!!!!!!x         x!!!!!x    o                 xx!!!!!!xx x!!                  xy     yx                     ",
   "!!!!x x!!!!!!x         x!!!!!x                     yx!!!!!!xx  xvv  xxx              xyxxxyx                      ",
   "!!!!x x!!!!!!x         x!!!!!xx                   xx!!!!!!xx   x                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxxxxxxxxxxxxx!!!!!!!xx    x                                                  ",
   "!!!!x x!!!!!!x|||||||||x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                              ",
   "                             xxx xxx xxx xxx     o o  x!!!!!!!!!!!!!!x                                        ",
   "                             x xxx x x xxx x          x!!!!!!!!!!!!!!x                                        ",
   "                             x             x   xxxxxxxxxxvvxxxxxxxxvvx                                        ",
   "                              xx         xx                                          xxx                      ",
   "                              x     x     x                                         x!!!x                     ",
   "                              x    xxx    x                                          xvx                      ",
   "                              x    xxx    xxxxxxx                        xxxxx                                ",
   "                              x           x                              x   x                                ",
   "                              xx         xx                              x x x                                ",
   "                                                  |xxxx|    |xxxx|     xxx xxx                                ",
   "                                   o o                                   x         xxx                        ",
   "                              xx         xx         oo        oo         xxx       x!!!=        oox           ",
   "                              x    yyy    x                            px x        xxx                        ",
   "                              xxxxxxxxxxxxx  x    x    x    x    x     xx xx                                  ",
   "         @                    x           x!!x    x!!!!x    x!!!!x    xx   xx                                 ",
   "xxxxxxxxxxxxxxxxxxxxxyyyyyyyyxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              ",
   "                                                                                                              "],
 ];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
